version: "3.8"

services:
  web:
    build: ..
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb3
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
